### ISSUE TITLE
关于合并所有yaml

### ISSUE THREAD

**Issue by cjydayang** [yjlch1016/yamlpy#1]
@yjlch1016 
想问一下为什么设计合并所有的yaml的数据并在每一个test都要跑一遍这种场景？是你的项目需要这样实现吗？感觉每个test可选yaml配置这样的方式更好一点

**Comment by yjlch1016** [comment]
合并所有的yaml文件是为了@pytest.mark.parametrize()传参，一次性传入，而不是多次分开传，因为我只有一个test方法；每个test方法对应一个yaml文件也可，但是那样需要写大量的代码，好处是可以定制化自由修改；我的思路是把测试用例的格式高度统一，后期维护时，不需要改代码，而是去修改yaml文件。
